# Generated by Django 5.1.3 on 2024-12-07 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_school_therapist'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
